name: my-check

on: push
jobs:
	build:
 	runs-on: ubunti-latest
	steps:
 	- uses: actions/chechout@v2
	- uses: actions/setup-node@v3
 		with:
	 		node-version: 18
	-	run: make setup
 	- run: make start
	- run: make lint
 	- run: make test
	- uses: JS-DevTools/npm-publish@v1
 		with:
	 		token: ${{ secrets.NPM_TOKEN }}
	